### ISSUE TITLE
commond line prblem

### ISSUE THREAD

**Issue by aashu122** [changeweb/Unifiedtransform#165]
composer install 
this commond is invalid 
autoload.php file doest show in any directory

**Comment by changeweb** [comment]
Your latest issue contains similar pojny. So I am closing this issue.

**Comment by nkatagithub** [comment]
auto load isnt in any directory. Tried checking for folder vendor/autoload.php and didnt find any. I also tried checking files and directiries to find autoload si as to reconfigure everything,... and still didnot find it. Looked thru all the issues and u just close all issues concerning this (i have seen two sofar). The issue is when you try generating key with artisan module u get an error on the execution of line 18 which requires autoload file that doesnot exist, i woundnt suggest commenting the line coz all other modules depend on it too. Sorry if iam abit rude.
