### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by ImNotKilian** [changeweb/Unifiedtransform#366]
Using Docker Container, typing the command `composer install` inside the `docker exec -it app sh` command. (Step 7 in Using Docker Container).

The error is:

`In Filesystem.php line 268:    /var/www/vendor does not exist and could not be created.`

Not sure how to fix this.

**Comment by ImNotKilian** [comment]
Fixed using `sudo chmod -R 777 .` and then trying again.

**Comment by yungifez** [comment]
Are you on production server?

**Comment by yungifez** [comment]
If you are on production server, please do note that running the said commend is dangerous in the sense that it allows anyone to read, write and execute whatever the hell they want 

This is very dangerous because your user data isn't safe and anyone can execute malicious code in the project 

If you are on development, its not really a bad thing since it's just you 

Happy coding

**Comment by ImNotKilian** [comment]
It's development, but what can I do if I want to run it on production server?

**Comment by ImNotKilian** [comment]
> If you are on production server, please do note that running the said commend is dangerous in the sense that it allows anyone to read, write and execute whatever the hell they want
> 
> This is very dangerous because your user data isn't safe and anyone can execute malicious code in the project
> 
> If you are on development, its not really a bad thing since it's just you
> 
> Happy coding

It's development, but what can I do if I want to run it on production server?

**Comment by yungifez** [comment]
You might have to read up setting environment permissions in production 

In laravel, users should only be entitled to the public folder of the app

And the public folder shouldn't even have the executable permission
